version: '3'
services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../application:/var/www/html
#    environment:
#      - DB_HOST=db
#      - DB_PORT=3306
#      - DB_DATABASE=laravel
#      - DB_USERNAME=root
#      - DB_PASSWORD=secret
  db:
    image: mysql:8
    container_name: db-80
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
  web:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../application:/var/www/html
    depends_on:
      - app
volumes:
  dbdata:
